### ISSUE TITLE
Highlight aria-label is not fully internationalized or translated

### ISSUE THREAD

**Issue by bethshook** [openstax/rex-web#1313]

**Comment by bethshook** [comment]
Missing Polish translations for:
`"i18n:highlighter:highlight:end": "End of {style, select, search {search result} other {{style}}} highlight"

"i18n:highlighter:highlight:start": "Start {style, select, search {search result} other {{style}}} highlight"`

We also need translations for the elements within curly braces.

**Comment by paulinaszczucinska** [comment]
"End of {style, select, search {search result} other {{style}}} highlight"
translation:
"Koniec {stylu, wyróżnienia, wyszukiwania {search result} innego {{style}}} dla zakreślenia". 

"Start {style, select, search {search result} other {{style}}} highlight"
translation:
"Początek {stylu, wyróżnienia, wyszukiwania {search result} innego {{style}}} dla zakreślenia".

If **{search result}** has to be translated as well, it should be {wyniku wyszukiwania}
same for **{{style}}** - it should be {{stylu}}
