### ISSUE TITLE
Add pyup config to automate upgrading python dependencies

### ISSUE THREAD

**Issue by m1yag1** [openstax/rex-web#132]
At the moment dependencies need to be upgraded manually. This is not great because currently the python stuff is in its own directory and isolated. This will make it easy to forget that dependencies need to be upgraded. I'd like pyup to conduct monthly checks for updates.

**Comment by TomWoodward** [comment]
@m1yag1 i'm putting an estimate of 1 on this, if thats too low for the work you did go ahead and change it
