### ISSUE TITLE
It's possible to make multiple highlights over the same search highlight

### ISSUE THREAD

**Issue by firadecki** [openstax/rex-web#1572]
# Description
We are able to make multiple highlights over the same search highlight without any errors and MH shows all those multiple highlight entries.

**To Reproduce**
Steps to reproduce the behavior are:
1. https://openstax.org/books/college-physics/pages/2-introduction-to-one-dimensional-kinematics
2. Search for velocity
3. Highlight over the same search result multiple times
Issue: We are able to make multiple highlights over the same search highlight without any errors and MH shows all those multiple highlight entries.

**Expected behavior**
We are not able to make multiple highlights over the same search highlight

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

# Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**User is not able to make multiple highlights over the same search highlight** 
**Highlighting**
> GIVEN Login {base_url}/books/college-physics/pages/2-introduction-to-one-dimensional-kinematics
> WHEN Search for velocity
> AND Highlight over the search result
> AND Try to highlight over the same search result again
> THEN something  

# Approvals
1A-PRE DESIGN
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

2B-REVIEW
  - [ ] Developer approves change
  - [ ] UX approves change
  - [ ] QA approves change
  - [ ] QA verifies that the acceptance tests are imported into TestRail
  - [ ] PDM approves change

# Process 
[Work Management for Unified](https://github.com/openstax/unified/blob/master/CONTRIBUTING.md)

**Comment by RoyEJohnson** [comment]
I can't reproduce the problem now (Chrome, Mac desktop). Is it fixed?

**Comment by ewaforman** [comment]
Works fine.
