### ISSUE TITLE
Fix math in practice questions content

### ISSUE THREAD

**Issue by KarinaMendez2** [openstax/rex-web#945]
Currently we use `mathml` for math content:
![image.png](https://images.zenhubusercontent.com/5c54789f0a972e6fd1ece1a0/edb29013-b4c7-4e3f-b20f-875a8290c393)

but practice questions test data uses `latex`, we need to adapt the `ContentExcerpt` to be able to read this format.

![image.png](https://images.zenhubusercontent.com/5c54789f0a972e6fd1ece1a0/be0fc029-767d-4436-a3dd-0c126fa11136)

pipeline:
review:
- [x] no product changes

pull requests:
- [ ] openstax/rex-web#952

**Comment by kjdav** [comment]
@TomWoodward did you want piotr to do implementation notes for this one after the navigation card?

**Comment by kjdav** [comment]
tom says yes to above. @PiotrKozlowski please prioritize writing implementation notes for this one after you finish the navigation card.

**Comment by PiotrKozlowski** [comment]
@kjdav I'll try to write this tomorrow morning because I would like @TomWoodward to review the notes before the thanksgiving break

**Comment by PiotrKozlowski** [comment]
### Implementation notes

`StudyGuides.tsx` and `Highlights.tsx` components uses this code to typeset the math:
```ts
React.useLayoutEffect(() => {
    if (container.current) {
      services.promiseCollector.add(allImagesLoaded(container.current));
      services.promiseCollector.add(typesetMath(container.current, assertWindow()));
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps, ignore promiseCollector
  }, [orderedStudyGuides]);
```
We wshould add something similar for the `Question.tsx` component

**Comment by TomWoodward** [comment]
@PiotrKozlowski when karina tried this with mathml content it worked in her question component, so i'm afraid there might be something else we need to change in the mathjax implementation, but yes this change you've proposed sounds like a good start

**Comment by PiotrKozlowski** [comment]
@TomWoodward I think some browsers are rendering MathML as a standard right now. It could be a case there

**Comment by TomWoodward** [comment]
firefox does, i don't think chrome does. just keep in mind that there could be more issues than just what you outlined above. we can start work and circle back to talking if needed
